// import {
// 	texasAbout,
// 	texasBenefits,
// 	texasCost,
// 	texasHero,
// 	texasSchools,
// 	texasStats,
// 	texasTopCities,
// 	texasUniversities,
// 	texasVacation,
// 	texasWhereToWork,
// 	texasWhodBeSuited,
// } from './texasStore';
// import {
// 	alabamaAbout,
// 	alabamaBenefits,
// 	alabamaCost,
// 	alabamaHero,
// 	alabamaSchools,
// 	alabamaStats,
// 	alabamaTopCities,
// 	alabamaUniversities,
// 	alabamaVacation,
// 	alabamaWhereToWork,
// 	alabamaWhodBeSuited,
// } from './alabamaStore';
// import {
// 	alaskaAbout,
// 	alaskaBenefits,
// 	alaskaCost,
// 	alaskaHero,
// 	alaskaSchools,
// 	alaskaStats,
// 	alaskaTopCities,
// 	alaskaUniversities,
// 	alaskaVacation,
// 	alaskaWhereToWork,
// 	alaskaWhodBeSuited,
// } from './alaskaStore';
// import {
// 	arizonaAbout,
// 	arizonaBenefits,
// 	arizonaCost,
// 	arizonaHero,
// 	arizonaSchools,
// 	arizonaStats,
// 	arizonaTopCities,
// 	arizonaUniversities,
// 	arizonaVacation,
// 	arizonaWhereToWork,
// 	arizonaWhodBeSuited,
// } from './arizonaStore';
// import {
// 	arkansasAbout,
// 	arkansasBenefits,
// 	arkansasCost,
// 	arkansasHero,
// 	arkansasSchools,
// 	arkansasStats,
// 	arkansasTopCities,
// 	arkansasUniversities,
// 	arkansasVacation,
// 	arkansasWhereToWork,
// 	arkansasWhodBeSuited,
// } from './arkansasStore';
// import {
// 	californiaAbout,
// 	californiaBenefits,
// 	californiaCost,
// 	californiaHero,
// 	californiaSchools,
// 	californiaStats,
// 	californiaTopCities,
// 	californiaUniversities,
// 	californiaVacation,
// 	californiaWhereToWork,
// 	californiaWhodBeSuited,
// } from './californiaStore';
// import {
// 	coloradoAbout,
// 	coloradoBenefits,
// 	coloradoCost,
// 	coloradoHero,
// 	coloradoSchools,
// 	coloradoStats,
// 	coloradoTopCities,
// 	coloradoUniversities,
// 	coloradoVacation,
// 	coloradoWhereToWork,
// 	coloradoWhodBeSuited,
// } from './coloradoStore';
// import {
// 	connecticutAbout,
// 	connecticutBenefits,
// 	connecticutCost,
// 	connecticutHero,
// 	connecticutSchools,
// 	connecticutStats,
// 	connecticutTopCities,
// 	connecticutUniversities,
// 	connecticutVacation,
// 	connecticutWhereToWork,
// 	connecticutWhodBeSuited,
// } from './connecticutStore';
// import {
// 	delawareAbout,
// 	delawareBenefits,
// 	delawareCost,
// 	delawareHero,
// 	delawareSchools,
// 	delawareStats,
// 	delawareTopCities,
// 	delawareUniversities,
// 	delawareVacation,
// 	delawareWhereToWork,
// 	delawareWhodBeSuited,
// } from './delawareStore';
// import {
// 	floridaAbout,
// 	floridaBenefits,
// 	floridaCost,
// 	floridaHero,
// 	floridaSchools,
// 	floridaStats,
// 	floridaTopCities,
// 	floridaUniversities,
// 	floridaVacation,
// 	floridaWhereToWork,
// 	floridaWhodBeSuited,
// } from './floridaStore';
// import {
// 	georgiaAbout,
// 	georgiaBenefits,
// 	georgiaCost,
// 	georgiaHero,
// 	georgiaSchools,
// 	georgiaStats,
// 	georgiaTopCities,
// 	georgiaUniversities,
// 	georgiaVacation,
// 	georgiaWhereToWork,
// 	georgiaWhodBeSuited,
// } from './georgiaStore';
// import {
// 	hawaiiAbout,
// 	hawaiiBenefits,
// 	hawaiiCost,
// 	hawaiiHero,
// 	hawaiiSchools,
// 	hawaiiStats,
// 	hawaiiTopCities,
// 	hawaiiUniversities,
// 	hawaiiVacation,
// 	hawaiiWhereToWork,
// 	hawaiiWhodBeSuited,
// } from './hawaiiStore';
// import {
// 	idahoAbout,
// 	idahoBenefits,
// 	idahoCost,
// 	idahoHero,
// 	idahoSchools,
// 	idahoStats,
// 	idahoTopCities,
// 	idahoUniversities,
// 	idahoVacation,
// 	idahoWhereToWork,
// 	idahoWhodBeSuited,
// } from './idahoStore';
// import {
// 	IllinoisAbout,
// 	IllinoisBenefits,
// 	IllinoisCost,
// 	IllinoisHero,
// 	IllinoisSchools,
// 	IllinoisStats,
// 	IllinoisTopCities,
// 	IllinoisUniversities,
// 	IllinoisVacation,
// 	IllinoisWhereToWork,
// 	IllinoisWhodBeSuited,
// } from './IllinoisStore';
// import {
// 	indianaAbout,
// 	indianaBenefits,
// 	indianaCost,
// 	indianaHero,
// 	indianaSchools,
// 	indianaStats,
// 	indianaTopCities,
// 	indianaUniversities,
// 	indianaVacation,
// 	indianaWhereToWork,
// 	indianaWhodBeSuited,
// } from './indianaStore';
// import {
// 	iowaAbout,
// 	iowaBenefits,
// 	iowaCost,
// 	iowaHero,
// 	iowaSchools,
// 	iowaStats,
// 	iowaTopCities,
// 	iowaUniversities,
// 	iowaVacation,
// 	iowaWhereToWork,
// 	iowaWhodBeSuited,
// } from './iowaStore';
// import {
// 	kansasAbout,
// 	kansasBenefits,
// 	kansasCost,
// 	kansasHero,
// 	kansasSchools,
// 	kansasStats,
// 	kansasTopCities,
// 	kansasUniversities,
// 	kansasVacation,
// 	kansasWhereToWork,
// 	kansasWhodBeSuited,
// } from './kansasStore';
// import {
// 	kentuckyAbout,
// 	kentuckyBenefits,
// 	kentuckyCost,
// 	kentuckyHero,
// 	kentuckySchools,
// 	kentuckyStats,
// 	kentuckyTopCities,
// 	kentuckyUniversities,
// 	kentuckyVacation,
// 	kentuckyWhereToWork,
// 	kentuckyWhodBeSuited,
// } from './kentuckyStore';
// import {
// 	louisianaAbout,
// 	louisianaBenefits,
// 	louisianaCost,
// 	louisianaHero,
// 	louisianaSchools,
// 	louisianaStats,
// 	louisianaTopCities,
// 	louisianaUniversities,
// 	louisianaVacation,
// 	louisianaWhereToWork,
// 	louisianaWhodBeSuited,
// } from './louisianaStore';
// import {
// 	maineAbout,
// 	maineBenefits,
// 	maineCost,
// 	maineHero,
// 	maineSchools,
// 	maineStats,
// 	maineTopCities,
// 	maineUniversities,
// 	maineVacation,
// 	maineWhereToWork,
// 	maineWhodBeSuited,
// } from './maineStore';
// import {
// 	marylandAbout,
// 	marylandBenefits,
// 	marylandCost,
// 	marylandHero,
// 	marylandSchools,
// 	marylandStats,
// 	marylandTopCities,
// 	marylandUniversities,
// 	marylandVacation,
// 	marylandWhereToWork,
// 	marylandWhodBeSuited,
// } from './marylandStore';
// import {
// 	massachusettsAbout,
// 	massachusettsBenefits,
// 	massachusettsCost,
// 	massachusettsHero,
// 	massachusettsSchools,
// 	massachusettsStats,
// 	massachusettsTopCities,
// 	massachusettsUniversities,
// 	massachusettsVacation,
// 	massachusettsWhereToWork,
// 	massachusettsWhodBeSuited,
// } from './massachusettsStore';
// import {
// 	michiganAbout,
// 	michiganBenefits,
// 	michiganCost,
// 	michiganHero,
// 	michiganSchools,
// 	michiganStats,
// 	michiganTopCities,
// 	michiganUniversities,
// 	michiganVacation,
// 	michiganWhereToWork,
// 	michiganWhodBeSuited,
// } from './michiganStore';
// import {
// 	minnesotaAbout,
// 	minnesotaBenefits,
// 	minnesotaCost,
// 	minnesotaHero,
// 	minnesotaSchools,
// 	minnesotaStats,
// 	minnesotaTopCities,
// 	minnesotaUniversities,
// 	minnesotaVacation,
// 	minnesotaWhereToWork,
// 	minnesotaWhodBeSuited,
// } from './minnesotaStore';
// import {
// 	mississippiAbout,
// 	mississippiBenefits,
// 	mississippiCost,
// 	mississippiHero,
// 	mississippiSchools,
// 	mississippiStats,
// 	mississippiTopCities,
// 	mississippiUniversities,
// 	mississippiVacation,
// 	mississippiWhereToWork,
// 	mississippiWhodBeSuited,
// } from './mississippiStore';
// import {
// 	missouriAbout,
// 	missouriBenefits,
// 	missouriCost,
// 	missouriHero,
// 	missouriSchools,
// 	missouriStats,
// 	missouriTopCities,
// 	missouriUniversities,
// 	missouriVacation,
// 	missouriWhereToWork,
// 	missouriWhodBeSuited,
// } from './missouriStore';
// import {
// 	montanaAbout,
// 	montanaBenefits,
// 	montanaCost,
// 	montanaHero,
// 	montanaSchools,
// 	montanaStats,
// 	montanaTopCities,
// 	montanaUniversities,
// 	montanaVacation,
// 	montanaWhereToWork,
// 	montanaWhodBeSuited,
// } from './montanaStore';
// import {
// 	nebraskaAbout,
// 	nebraskaBenefits,
// 	nebraskaCost,
// 	nebraskaHero,
// 	nebraskaSchools,
// 	nebraskaStats,
// 	nebraskaTopCities,
// 	nebraskaUniversities,
// 	nebraskaVacation,
// 	nebraskaWhereToWork,
// 	nebraskaWhodBeSuited,
// } from './nebraskaStore';
// import {
// 	nevadaAbout,
// 	nevadaBenefits,
// 	nevadaCost,
// 	nevadaHero,
// 	nevadaSchools,
// 	nevadaStats,
// 	nevadaTopCities,
// 	nevadaUniversities,
// 	nevadaVacation,
// 	nevadaWhereToWork,
// 	nevadaWhodBeSuited,
// } from './nevadaStore';
// import {
// 	newhampshireAbout,
// 	newhampshireBenefits,
// 	newhampshireCost,
// 	newhampshireHero,
// 	newhampshireSchools,
// 	newhampshireStats,
// 	newhampshireTopCities,
// 	newhampshireUniversities,
// 	newhampshireVacation,
// 	newhampshireWhereToWork,
// 	newhampshireWhodBeSuited,
// } from './new-hampshireStore';
// import {
// 	newJerseyAbout,
// 	newJerseyBenefits,
// 	newJerseyCost,
// 	newJerseyHero,
// 	newJerseySchools,
// 	newJerseyStats,
// 	newJerseyTopCities,
// 	newJerseyUniversities,
// 	newJerseyVacation,
// 	newJerseyWhereToWork,
// 	newJerseyWhodBeSuited,
// } from './newJerseyStore';
// import {
// 	newMexicoAbout,
// 	newMexicoBenefits,
// 	newMexicoCost,
// 	newMexicoHero,
// 	newMexicoSchools,
// 	newMexicoStats,
// 	newMexicoTopCities,
// 	newMexicoUniversities,
// 	newMexicoVacation,
// 	newMexicoWhereToWork,
// 	newMexicoWhodBeSuited,
// } from './newMexicoStore';
// import {
// 	newYorkAbout,
// 	newYorkBenefits,
// 	newYorkCost,
// 	newYorkHero,
// 	newYorkSchools,
// 	newYorkStats,
// 	newYorkTopCities,
// 	newYorkUniversities,
// 	newYorkVacation,
// 	newYorkWhereToWork,
// 	newYorkWhodBeSuited,
// } from './newYorkStore';
// import {
// 	northCarolinaAbout,
// 	northCarolinaBenefits,
// 	northCarolinaCost,
// 	northCarolinaHero,
// 	northCarolinaSchools,
// 	northCarolinaStats,
// 	northCarolinaTopCities,
// 	northCarolinaUniversities,
// 	northCarolinaVacation,
// 	northCarolinaWhereToWork,
// 	northCarolinaWhodBeSuited,
// } from './northCarolinaStore';
// import {
// 	northDakotaAbout,
// 	northDakotaBenefits,
// 	northDakotaCost,
// 	northDakotaHero,
// 	northDakotaSchools,
// 	northDakotaStats,
// 	northDakotaTopCities,
// 	northDakotaUniversities,
// 	northDakotaVacation,
// 	northDakotaWhereToWork,
// 	northDakotaWhodBeSuited,
// } from './northDakotaStore';
// import {
// 	ohioAbout,
// 	ohioBenefits,
// 	ohioCost,
// 	ohioHero,
// 	ohioSchools,
// 	ohioStats,
// 	ohioTopCities,
// 	ohioUniversities,
// 	ohioVacation,
// 	ohioWhereToWork,
// 	ohioWhodBeSuited,
// } from './ohioStore';
// import {
// 	oklahomaAbout,
// 	oklahomaBenefits,
// 	oklahomaCost,
// 	oklahomaHero,
// 	oklahomaSchools,
// 	oklahomaStats,
// 	oklahomaTopCities,
// 	oklahomaUniversities,
// 	oklahomaVacation,
// 	oklahomaWhereToWork,
// 	oklahomaWhodBeSuited,
// } from './oklahomaStore';
// import {
// 	oregonAbout,
// 	oregonBenefits,
// 	oregonCost,
// 	oregonHero,
// 	oregonSchools,
// 	oregonStats,
// 	oregonTopCities,
// 	oregonUniversities,
// 	oregonVacation,
// 	oregonWhereToWork,
// 	oregonWhodBeSuited,
// } from './oregonStore';
// import {
// 	pennsylvaniaAbout,
// 	pennsylvaniaBenefits,
// 	pennsylvaniaCost,
// 	pennsylvaniaHero,
// 	pennsylvaniaSchools,
// 	pennsylvaniaStats,
// 	pennsylvaniaTopCities,
// 	pennsylvaniaUniversities,
// 	pennsylvaniaVacation,
// 	pennsylvaniaWhereToWork,
// 	pennsylvaniaWhodBeSuited,
// } from './pennsylvaniaStore';
// import {
// 	rhodeIslandAbout,
// 	rhodeIslandBenefits,
// 	rhodeIslandCost,
// 	rhodeIslandHero,
// 	rhodeIslandSchools,
// 	rhodeIslandStats,
// 	rhodeIslandTopCities,
// 	rhodeIslandUniversities,
// 	rhodeIslandVacation,
// 	rhodeIslandWhereToWork,
// 	rhodeIslandWhodBeSuited,
// } from './rhodeIslandStore';
// import {
// 	southCarolinaAbout,
// 	southCarolinaBenefits,
// 	southCarolinaCost,
// 	southCarolinaHero,
// 	southCarolinaSchools,
// 	southCarolinaStats,
// 	southCarolinaTopCities,
// 	southCarolinaUniversities,
// 	southCarolinaVacation,
// 	southCarolinaWhereToWork,
// 	southCarolinaWhodBeSuited,
// } from './southCarolinaStore';
// import {
// 	southDakotaAbout,
// 	southDakotaBenefits,
// 	southDakotaCost,
// 	southDakotaHero,
// 	southDakotaSchools,
// 	southDakotaStats,
// 	southDakotaTopCities,
// 	southDakotaUniversities,
// 	southDakotaVacation,
// 	southDakotaWhereToWork,
// 	southDakotaWhodBeSuited,
// } from './southDakotaStore';
// import {
// 	tennesseeAbout,
// 	tennesseeBenefits,
// 	tennesseeCost,
// 	tennesseeHero,
// 	tennesseeSchools,
// 	tennesseeStats,
// 	tennesseeTopCities,
// 	tennesseeUniversities,
// 	tennesseeVacation,
// 	tennesseeWhereToWork,
// 	tennesseeWhodBeSuited,
// } from './tennesseeStore';
// import {
// 	utahAbout,
// 	utahBenefits,
// 	utahCost,
// 	utahHero,
// 	utahSchools,
// 	utahStats,
// 	utahTopCities,
// 	utahUniversities,
// 	utahVacation,
// 	utahWhereToWork,
// 	utahWhodBeSuited,
// } from './utahStore';
// import {
// 	vermontAbout,
// 	vermontBenefits,
// 	vermontCost,
// 	vermontHero,
// 	vermontSchools,
// 	vermontStats,
// 	vermontTopCities,
// 	vermontUniversities,
// 	vermontVacation,
// 	vermontWhereToWork,
// 	vermontWhodBeSuited,
// } from './vermontStore';
// import {
// 	virginiaAbout,
// 	virginiaBenefits,
// 	virginiaCost,
// 	virginiaHero,
// 	virginiaSchools,
// 	virginiaStats,
// 	virginiaTopCities,
// 	virginiaUniversities,
// 	virginiaVacation,
// 	virginiaWhereToWork,
// 	virginiaWhodBeSuited,
// } from './virginiaStore';
// import {
// 	washingtonAbout,
// 	washingtonBenefits,
// 	washingtonCost,
// 	washingtonHero,
// 	washingtonSchools,
// 	washingtonStats,
// 	washingtonTopCities,
// 	washingtonUniversities,
// 	washingtonVacation,
// 	washingtonWhereToWork,
// 	washingtonWhodBeSuited,
// } from './washingtonStore';
// import {
// 	westVirginiaAbout,
// 	westVirginiaBenefits,
// 	westVirginiaCost,
// 	westVirginiaHero,
// 	westVirginiaSchools,
// 	westVirginiaStats,
// 	westVirginiaTopCities,
// 	westVirginiaUniversities,
// 	westVirginiaVacation,
// 	westVirginiaWhereToWork,
// 	westVirginiaWhodBeSuited,
// } from './westVirginiaStore';
// import {
// 	wisconsinAbout,
// 	wisconsinBenefits,
// 	wisconsinCost,
// 	wisconsinHero,
// 	wisconsinSchools,
// 	wisconsinStats,
// 	wisconsinTopCities,
// 	wisconsinUniversities,
// 	wisconsinVacation,
// 	wisconsinWhereToWork,
// 	wisconsinWhodBeSuited,
// } from './wisconsinStore';
// import {
// 	wyomingAbout,
// 	wyomingBenefits,
// 	wyomingCost,
// 	wyomingHero,
// 	wyomingSchools,
// 	wyomingStats,
// 	wyomingTopCities,
// 	wyomingUniversities,
// 	wyomingVacation,
// 	wyomingWhereToWork,
// 	wyomingWhodBeSuited,
// } from './wyomingStore';

// // interfaces
// import { ISEOAbout } from '@/components/guides/seoAbout';
// import { ISEOBenefits } from '@/components/guides/seoBenefits';
// import { ISEOCost } from '@/components/guides/seoCost';
// import { ISEOEducation } from '@/components/guides/seoEducation';
// import { ISEOHero } from '@/components/guides/seoHero';
// import { ISEOStats } from '@/components/guides/seoStats';
// import { ISEOTopCities } from '@/components/guides/seoTopCities';
// import { ISEOVacaiton } from '@/components/guides/seoVacation';
// import { ISEOWhereToWork } from '@/components/guides/seoWhereToWork';
// import { ISEOWhodBeSuited } from '@/components/guides/seoWhodBeSuited';
// export interface ISEOPage {
// 	slug: string;
// 	metaTitle: string;
// 	metaDescription: string;
// 	hero: ISEOHero;
// 	about: ISEOAbout;
// 	stats: ISEOStats;
// 	benefits: ISEOBenefits;
// 	cost: ISEOCost;
// 	whodBeSuited: ISEOWhodBeSuited;
// 	topCities: ISEOTopCities;
// 	schools: ISEOEducation;
// 	universities: ISEOEducation;
// 	whereToWork: ISEOWhereToWork;
// 	vacation: ISEOVacaiton;
// }

// export const guides: ISEOPage[] = [
// 	{
// 		slug: 'texas',
// 		metaTitle: 'Professional Dallas Moving Services | Star Van Lines Movers',
// 		metaDescription:
// 			'Looking for reliable moving services in Dallas, Texas? Star Van Lines Movers is your trusted partner for all your moving needs. Our experienced Dallas movers provide efficient and professional services, ensuring a smooth relocation process. Contact us today for top-notch moving companies in the Dallas area.',
// 		hero: texasHero,
// 		about: texasAbout,
// 		stats: texasStats,
// 		benefits: texasBenefits,
// 		cost: texasCost,
// 		whodBeSuited: texasWhodBeSuited,
// 		topCities: texasTopCities,
// 		schools: texasSchools,
// 		universities: texasUniversities,
// 		whereToWork: texasWhereToWork,
// 		vacation: texasVacation,
// 	},
// 	{
// 		slug: 'alabama',
// 		metaTitle: 'Trusted Movers from Los Angeles to Alabama | Star Van Lines Movers',
// 		metaDescription:
// 			' Moving from Los Angeles to Alabama? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in Alabama.',
// 		hero: alabamaHero,
// 		about: alabamaAbout,
// 		stats: alabamaStats,
// 		benefits: alabamaBenefits,
// 		cost: alabamaCost,
// 		whodBeSuited: alabamaWhodBeSuited,
// 		topCities: alabamaTopCities,
// 		schools: alabamaSchools,
// 		universities: alabamaUniversities,
// 		whereToWork: alabamaWhereToWork,
// 		vacation: alabamaVacation,
// 	},
// 	{
// 		slug: 'alaska',
// 		metaTitle: 'Reliable Movers from Alaska to California | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from Alaska to California? Trust Star Van Lines Movers for reliable and efficient moving services. Our experienced team will handle every aspect of your move, ensuring a seamless transition to your new home in California.',
// 		hero: alaskaHero,
// 		about: alaskaAbout,
// 		stats: alaskaStats,
// 		benefits: alaskaBenefits,
// 		cost: alaskaCost,
// 		whodBeSuited: alaskaWhodBeSuited,
// 		topCities: alaskaTopCities,
// 		schools: alaskaSchools,
// 		universities: alaskaUniversities,
// 		whereToWork: alaskaWhereToWork,
// 		vacation: alaskaVacation,
// 	},
// 	{
// 		slug: 'arizona',
// 		metaTitle: 'Reliable Moving Services in Phoenix, AZ | Star Van Lines',
// 		metaDescription:
// 			'Planning a move in Phoenix, AZ? Trust Star Van Lines for reliable and professional moving services. Our experienced team specializes in handling all aspects of your move, ensuring a seamless transition to your new home. Discover our trusted moving services in Phoenix, AZ. Contact us today!',
// 		hero: arizonaHero,
// 		about: arizonaAbout,
// 		stats: arizonaStats,
// 		benefits: arizonaBenefits,
// 		cost: arizonaCost,
// 		whodBeSuited: arizonaWhodBeSuited,
// 		topCities: arizonaTopCities,
// 		schools: arizonaSchools,
// 		universities: arizonaUniversities,
// 		whereToWork: arizonaWhereToWork,
// 		vacation: arizonaVacation,
// 	},
// 	{
// 		slug: 'arkansas',
// 		metaTitle: 'Trusted Movers from Los Angeles to Arkansas | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from Los Angeles to Arkansas? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in Arkansas.',
// 		hero: arkansasHero,
// 		about: arkansasAbout,
// 		stats: arkansasStats,
// 		benefits: arkansasBenefits,
// 		cost: arkansasCost,
// 		whodBeSuited: arkansasWhodBeSuited,
// 		topCities: arkansasTopCities,
// 		schools: arkansasSchools,
// 		universities: arkansasUniversities,
// 		whereToWork: arkansasWhereToWork,
// 		vacation: arkansasVacation,
// 	},
// 	{
// 		slug: 'california',
// 		metaTitle: 'Reliable Moving Service in California | Star Van Lines',
// 		metaDescription:
// 			"Need a reliable moving service in California? Star Van Lines is here to assist you. Our dedicated team of professionals specializes in providing dependable moving services across the state. Whether it's a residential or commercial move, trust us for a stress-free and efficient relocation experience. Contact us for reliable moving services in California.",
// 		hero: californiaHero,
// 		about: californiaAbout,
// 		stats: californiaStats,
// 		benefits: californiaBenefits,
// 		cost: californiaCost,
// 		whodBeSuited: californiaWhodBeSuited,
// 		topCities: californiaTopCities,
// 		schools: californiaSchools,
// 		universities: californiaUniversities,
// 		whereToWork: californiaWhereToWork,
// 		vacation: californiaVacation,
// 	},
// 	{
// 		slug: 'colorado',
// 		metaTitle: 'Smooth Moving from Colorado to Los Angeles | Star Van Lines Movers',
// 		metaDescription:
// 			'Planning a move from Colorado to Los Angeles? Trust Star Van Lines Movers for a smooth and stress-free relocation. Our experienced team of movers will handle every aspect of your move, ensuring a seamless transition to your new home.',
// 		hero: coloradoHero,
// 		about: coloradoAbout,
// 		stats: coloradoStats,
// 		benefits: coloradoBenefits,
// 		cost: coloradoCost,
// 		whodBeSuited: coloradoWhodBeSuited,
// 		topCities: coloradoTopCities,
// 		schools: coloradoSchools,
// 		universities: coloradoUniversities,
// 		whereToWork: coloradoWhereToWork,
// 		vacation: coloradoVacation,
// 	},
// 	{
// 		slug: 'connecticut',
// 		metaTitle: 'Smooth Moving from California to Connecticut | Star Van Lines Movers',
// 		metaDescription:
// 			'Planning a move from California to Connecticut? Trust Star Van Lines Movers for a smooth and stress-free relocation. Our experienced team of movers will handle every aspect of your move, ensuring a seamless transition to your new home.',
// 		hero: connecticutHero,
// 		about: connecticutAbout,
// 		stats: connecticutStats,
// 		benefits: connecticutBenefits,
// 		cost: connecticutCost,
// 		whodBeSuited: connecticutWhodBeSuited,
// 		topCities: connecticutTopCities,
// 		schools: connecticutSchools,
// 		universities: connecticutUniversities,
// 		whereToWork: connecticutWhereToWork,
// 		vacation: connecticutVacation,
// 	},
// 	{
// 		slug: 'delaware',
// 		metaTitle: 'Trusted Movers from Los Angeles to Delaware | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from Los Angeles to Delaware? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in Delaware.',
// 		hero: delawareHero,
// 		about: delawareAbout,
// 		stats: delawareStats,
// 		benefits: delawareBenefits,
// 		cost: delawareCost,
// 		whodBeSuited: delawareWhodBeSuited,
// 		topCities: delawareTopCities,
// 		schools: delawareSchools,
// 		universities: delawareUniversities,
// 		whereToWork: delawareWhereToWork,
// 		vacation: delawareVacation,
// 	},
// 	{
// 		slug: 'florida',
// 		metaTitle: 'Trusted Florida Movers | Star Van Lines Movers',
// 		metaDescription:
// 			'Planning a move to or within Florida? Look no further than Star Van Lines Movers, your trusted Florida movers. With our expertise and commitment to customer satisfaction, we ensure a seamless and stress-free moving experience. Contact us today for reliable moving companies based in Florida and make your relocation a breeze.',
// 		hero: floridaHero,
// 		about: floridaAbout,
// 		stats: floridaStats,
// 		benefits: floridaBenefits,
// 		cost: floridaCost,
// 		whodBeSuited: floridaWhodBeSuited,
// 		topCities: floridaTopCities,
// 		schools: floridaSchools,
// 		universities: floridaUniversities,
// 		whereToWork: floridaWhereToWork,
// 		vacation: floridaVacation,
// 	},
// 	{
// 		slug: 'georgia',
// 		metaTitle: 'Smooth Moving from Georgia to California | Star Van Lines Movers',
// 		metaDescription:
// 			'Planning a move from Georgia to California? Trust Star Van Lines Movers for a smooth and stress-free relocation. Our experienced team of movers will handle every aspect of your move, ensuring a seamless transition to your new home.',
// 		hero: georgiaHero,
// 		about: georgiaAbout,
// 		stats: georgiaStats,
// 		benefits: georgiaBenefits,
// 		cost: georgiaCost,
// 		whodBeSuited: georgiaWhodBeSuited,
// 		topCities: georgiaTopCities,
// 		schools: georgiaSchools,
// 		universities: georgiaUniversities,
// 		whereToWork: georgiaWhereToWork,
// 		vacation: georgiaVacation,
// 	},
// 	{
// 		slug: 'hawaii',
// 		metaTitle: 'Reliable Movers from Hawaii to California | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from Hawaii to California? Trust Star Van Lines Movers for reliable and efficient moving services. Our experienced team will handle every aspect of your move, ensuring a seamless transition to your new home in California.',
// 		hero: hawaiiHero,
// 		about: hawaiiAbout,
// 		stats: hawaiiStats,
// 		benefits: hawaiiBenefits,
// 		cost: hawaiiCost,
// 		whodBeSuited: hawaiiWhodBeSuited,
// 		topCities: hawaiiTopCities,
// 		schools: hawaiiSchools,
// 		universities: hawaiiUniversities,
// 		whereToWork: hawaiiWhereToWork,
// 		vacation: hawaiiVacation,
// 	},
// 	{
// 		slug: 'idaho',
// 		metaTitle: 'Trusted Moving Companies in Boise, Idaho | Star Van Lines Movers',
// 		metaDescription:
// 			'Star Van Lines Movers is your go-to choice for moving companies in Boise, Idaho. With our expert movers and exceptional service, we make your move stress-free and efficient. Contact us for the best movers in the Boise area.',
// 		hero: idahoHero,
// 		about: idahoAbout,
// 		stats: idahoStats,
// 		benefits: idahoBenefits,
// 		cost: idahoCost,
// 		whodBeSuited: idahoWhodBeSuited,
// 		topCities: idahoTopCities,
// 		schools: idahoSchools,
// 		universities: idahoUniversities,
// 		whereToWork: idahoWhereToWork,
// 		vacation: idahoVacation,
// 	},
// 	{
// 		slug: 'illinois',
// 		metaTitle: 'Trusted Movers in Chicago | Star Van Lines Movers',
// 		metaDescription:
// 			'Looking for reliable movers in Chicago? Star Van Lines Movers offers professional moving services in Chicago, IL, and surrounding areas. Get a free moving quote today!',
// 		hero: IllinoisHero,
// 		about: IllinoisAbout,
// 		stats: IllinoisStats,
// 		benefits: IllinoisBenefits,
// 		cost: IllinoisCost,
// 		whodBeSuited: IllinoisWhodBeSuited,
// 		topCities: IllinoisTopCities,
// 		schools: IllinoisSchools,
// 		universities: IllinoisUniversities,
// 		whereToWork: IllinoisWhereToWork,
// 		vacation: IllinoisVacation,
// 	},
// 	{
// 		slug: 'indiana',
// 		metaTitle: 'Trusted Movers from California to Indiana | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from California to Indiana? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in Indiana.',
// 		hero: indianaHero,
// 		about: indianaAbout,
// 		stats: indianaStats,
// 		benefits: indianaBenefits,
// 		cost: indianaCost,
// 		whodBeSuited: indianaWhodBeSuited,
// 		topCities: indianaTopCities,
// 		schools: indianaSchools,
// 		universities: indianaUniversities,
// 		whereToWork: indianaWhereToWork,
// 		vacation: indianaVacation,
// 	},
// 	{
// 		slug: 'iowa',
// 		metaTitle: 'Efficient Moving to Iowa from California | Star Van Lines Movers',
// 		metaDescription:
// 			'Star Van Lines Movers is your trusted choice for efficient moving from California to Iowa. With our expertise and dedication to customer satisfaction, we ensure a seamless and stress-free relocation.',
// 		hero: iowaHero,
// 		about: iowaAbout,
// 		stats: iowaStats,
// 		benefits: iowaBenefits,
// 		cost: iowaCost,
// 		whodBeSuited: iowaWhodBeSuited,
// 		topCities: iowaTopCities,
// 		schools: iowaSchools,
// 		universities: iowaUniversities,
// 		whereToWork: iowaWhereToWork,
// 		vacation: iowaVacation,
// 	},
// 	{
// 		slug: 'kansas',
// 		metaTitle: 'Local Movers in Kansas City | Star Van Lines Movers',
// 		metaDescription:
// 			'Star Van Lines Movers offers reliable local moving services in Kansas City. Our team of experienced movers is familiar with the area and will ensure a hassle-free and efficient move. Get a free quote today!',
// 		hero: kansasHero,
// 		about: kansasAbout,
// 		stats: kansasStats,
// 		benefits: kansasBenefits,
// 		cost: kansasCost,
// 		whodBeSuited: kansasWhodBeSuited,
// 		topCities: kansasTopCities,
// 		schools: kansasSchools,
// 		universities: kansasUniversities,
// 		whereToWork: kansasWhereToWork,
// 		vacation: kansasVacation,
// 	},
// 	{
// 		slug: 'kentucky',
// 		metaTitle: 'Smooth Moving to California from Kentucky | Star Van Lines Movers',
// 		metaDescription:
// 			'Planning a move to California from Kentucky? Trust Star Van Lines Movers for a smooth and stress-free relocation. Our experienced team of movers will handle every aspect of your move, ensuring a seamless transition to your new home.',
// 		hero: kentuckyHero,
// 		about: kentuckyAbout,
// 		stats: kentuckyStats,
// 		benefits: kentuckyBenefits,
// 		cost: kentuckyCost,
// 		whodBeSuited: kentuckyWhodBeSuited,
// 		topCities: kentuckyTopCities,
// 		schools: kentuckySchools,
// 		universities: kentuckyUniversities,
// 		whereToWork: kentuckyWhereToWork,
// 		vacation: kentuckyVacation,
// 	},
// 	{
// 		slug: 'louisiana',
// 		metaTitle: 'Trusted Movers from California to Louisiana | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from California to Louisiana? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in Louisiana.',
// 		hero: louisianaHero,
// 		about: louisianaAbout,
// 		stats: louisianaStats,
// 		benefits: louisianaBenefits,
// 		cost: louisianaCost,
// 		whodBeSuited: louisianaWhodBeSuited,
// 		topCities: louisianaTopCities,
// 		schools: louisianaSchools,
// 		universities: louisianaUniversities,
// 		whereToWork: louisianaWhereToWork,
// 		vacation: louisianaVacation,
// 	},
// 	{
// 		slug: 'maine',
// 		metaTitle: 'Trusted Movers from Los Angeles to Maine | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from Los Angeles to Maine? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in Maine.',
// 		hero: maineHero,
// 		about: maineAbout,
// 		stats: maineStats,
// 		benefits: maineBenefits,
// 		cost: maineCost,
// 		whodBeSuited: maineWhodBeSuited,
// 		topCities: maineTopCities,
// 		schools: maineSchools,
// 		universities: maineUniversities,
// 		whereToWork: maineWhereToWork,
// 		vacation: maineVacation,
// 	},
// 	{
// 		slug: 'maryland',
// 		metaTitle: 'Smooth Moving to California from Maryland | Star Van Lines Movers',
// 		metaDescription:
// 			'Planning a move to California from Maryland? Trust Star Van Lines Movers for a smooth and stress-free relocation. Our experienced team of movers will handle every aspect of your move, ensuring a seamless transition to your new home.',
// 		hero: marylandHero,
// 		about: marylandAbout,
// 		stats: marylandStats,
// 		benefits: marylandBenefits,
// 		cost: marylandCost,
// 		whodBeSuited: marylandWhodBeSuited,
// 		topCities: marylandTopCities,
// 		schools: marylandSchools,
// 		universities: marylandUniversities,
// 		whereToWork: marylandWhereToWork,
// 		vacation: marylandVacation,
// 	},
// 	{
// 		slug: 'massachusetts',
// 		metaTitle: 'Trusted Movers from Los Angeles to Massachusetts | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from Los Angeles to Massachusetts? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in Massachusetts.',
// 		hero: massachusettsHero,
// 		about: massachusettsAbout,
// 		stats: massachusettsStats,
// 		benefits: massachusettsBenefits,
// 		cost: massachusettsCost,
// 		whodBeSuited: massachusettsWhodBeSuited,
// 		topCities: massachusettsTopCities,
// 		schools: massachusettsSchools,
// 		universities: massachusettsUniversities,
// 		whereToWork: massachusettsWhereToWork,
// 		vacation: massachusettsVacation,
// 	},
// 	{
// 		slug: 'michigan',
// 		metaTitle: 'Smooth Moving from California to Michigan | Star Van Lines Movers',
// 		metaDescription:
// 			'Planning a move from California to Michigan? Trust Star Van Lines Movers for a smooth and stress-free relocation. Our experienced team of movers will handle every aspect of your move, ensuring a seamless transition to your new home.',
// 		hero: michiganHero,
// 		about: michiganAbout,
// 		stats: michiganStats,
// 		benefits: michiganBenefits,
// 		cost: michiganCost,
// 		whodBeSuited: michiganWhodBeSuited,
// 		topCities: michiganTopCities,
// 		schools: michiganSchools,
// 		universities: michiganUniversities,
// 		whereToWork: michiganWhereToWork,
// 		vacation: michiganVacation,
// 	},
// 	{
// 		slug: 'minnesota',
// 		metaTitle: 'Trusted Movers from Minnesota to California | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from Minnesota to California? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in California.',
// 		hero: minnesotaHero,
// 		about: minnesotaAbout,
// 		stats: minnesotaStats,
// 		benefits: minnesotaBenefits,
// 		cost: minnesotaCost,
// 		whodBeSuited: minnesotaWhodBeSuited,
// 		topCities: minnesotaTopCities,
// 		schools: minnesotaSchools,
// 		universities: minnesotaUniversities,
// 		whereToWork: minnesotaWhereToWork,
// 		vacation: minnesotaVacation,
// 	},
// 	{
// 		slug: 'mississippi',
// 		metaTitle: 'Smooth Moving from Mississippi to California | Star Van Lines Movers',
// 		metaDescription:
// 			'Planning a move from Mississippi to California? Trust Star Van Lines Movers for a smooth and hassle-free relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in California.',
// 		hero: mississippiHero,
// 		about: mississippiAbout,
// 		stats: mississippiStats,
// 		benefits: mississippiBenefits,
// 		cost: mississippiCost,
// 		whodBeSuited: mississippiWhodBeSuited,
// 		topCities: mississippiTopCities,
// 		schools: mississippiSchools,
// 		universities: mississippiUniversities,
// 		whereToWork: mississippiWhereToWork,
// 		vacation: mississippiVacation,
// 	},
// 	{
// 		slug: 'missouri',
// 		metaTitle: 'Trusted Movers from Missouri to California | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from Missouri to California? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in California.',
// 		hero: missouriHero,
// 		about: missouriAbout,
// 		stats: missouriStats,
// 		benefits: missouriBenefits,
// 		cost: missouriCost,
// 		whodBeSuited: missouriWhodBeSuited,
// 		topCities: missouriTopCities,
// 		schools: missouriSchools,
// 		universities: missouriUniversities,
// 		whereToWork: missouriWhereToWork,
// 		vacation: missouriVacation,
// 	},
// 	{
// 		slug: 'montana',
// 		metaTitle: 'Top Movers in Montana | Star Van Lines Movers',
// 		metaDescription:
// 			'Looking for reliable moving companies in Montana? Star Van Lines Movers offers professional house moving services across Montana. Contact us today for a stress-free moving experience.',
// 		hero: montanaHero,
// 		about: montanaAbout,
// 		stats: montanaStats,
// 		benefits: montanaBenefits,
// 		cost: montanaCost,
// 		whodBeSuited: montanaWhodBeSuited,
// 		topCities: montanaTopCities,
// 		schools: montanaSchools,
// 		universities: montanaUniversities,
// 		whereToWork: montanaWhereToWork,
// 		vacation: montanaVacation,
// 	},
// 	{
// 		slug: 'nebraska',
// 		metaTitle: 'Smooth Moving to California from Nebraska | Star Van Lines Movers',
// 		metaDescription:
// 			'Planning a move to California from Nebraska? Trust Star Van Lines Movers for a smooth and stress-free relocation. Our experienced team of movers will handle every aspect of your move, ensuring a seamless transition to your new home.',
// 		hero: nebraskaHero,
// 		about: nebraskaAbout,
// 		stats: nebraskaStats,
// 		benefits: nebraskaBenefits,
// 		cost: nebraskaCost,
// 		whodBeSuited: nebraskaWhodBeSuited,
// 		topCities: nebraskaTopCities,
// 		schools: nebraskaSchools,
// 		universities: nebraskaUniversities,
// 		whereToWork: nebraskaWhereToWork,
// 		vacation: nebraskaVacation,
// 	},
// 	{
// 		slug: 'nevada',
// 		metaTitle: 'Trusted Movers in Las Vegas, NV | Star Van Lines Movers',
// 		metaDescription:
// 			'Star Van Lines Movers is a trusted moving company in Las Vegas, NV. We offer reliable and efficient moving services to make your relocation a breeze. Request a free quote from our experienced movers!',
// 		hero: nevadaHero,
// 		about: nevadaAbout,
// 		stats: nevadaStats,
// 		benefits: nevadaBenefits,
// 		cost: nevadaCost,
// 		whodBeSuited: nevadaWhodBeSuited,
// 		topCities: nevadaTopCities,
// 		schools: nevadaSchools,
// 		universities: nevadaUniversities,
// 		whereToWork: nevadaWhereToWork,
// 		vacation: nevadaVacation,
// 	},
// 	{
// 		slug: 'new-hampshire',
// 		metaTitle: 'Trusted Movers from Los Angeles to New Hampshire | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from Los Angeles to New Hampshire? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in New Hampshire.',
// 		hero: newhampshireHero,
// 		about: newhampshireAbout,
// 		stats: newhampshireStats,
// 		benefits: newhampshireBenefits,
// 		cost: newhampshireCost,
// 		whodBeSuited: newhampshireWhodBeSuited,
// 		topCities: newhampshireTopCities,
// 		schools: newhampshireSchools,
// 		universities: newhampshireUniversities,
// 		whereToWork: newhampshireWhereToWork,
// 		vacation: newhampshireVacation,
// 	},
// 	{
// 		slug: 'new-jersey',
// 		metaTitle: 'Reliable Movers in Atlantic City, NJ | Star Van Lines Movers',
// 		metaDescription:
// 			'Planning a move to or within Atlantic City, NJ? Look no further than Star Van Lines Movers, your trusted partner for efficient and reliable moving services. Our experienced movers cater to Ocean City, Egg Harbor Township, and other areas in North Jersey. Trust Atlantic Movers LLC for a seamless relocation experience. Contact us today.',
// 		hero: newJerseyHero,
// 		about: newJerseyAbout,
// 		stats: newJerseyStats,
// 		benefits: newJerseyBenefits,
// 		cost: newJerseyCost,
// 		whodBeSuited: newJerseyWhodBeSuited,
// 		topCities: newJerseyTopCities,
// 		schools: newJerseySchools,
// 		universities: newJerseyUniversities,
// 		whereToWork: newJerseyWhereToWork,
// 		vacation: newJerseyVacation,
// 	},
// 	{
// 		slug: 'new-mexico',
// 		metaTitle: 'Trusted Movers from Los Angeles to New Mexico | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from Los Angeles to New Mexico? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in New Mexico.',
// 		hero: newMexicoHero,
// 		about: newMexicoAbout,
// 		stats: newMexicoStats,
// 		benefits: newMexicoBenefits,
// 		cost: newMexicoCost,
// 		whodBeSuited: newMexicoWhodBeSuited,
// 		topCities: newMexicoTopCities,
// 		schools: newMexicoSchools,
// 		universities: newMexicoUniversities,
// 		whereToWork: newMexicoWhereToWork,
// 		vacation: newMexicoVacation,
// 	},
// 	{
// 		slug: 'new-york',
// 		metaTitle: 'Trusted Movers in NYC | Reliable Moving Services',
// 		metaDescription:
// 			"If you're searching for reliable movers in NYC, look no further. Our professional moving services ensure a smooth and stress-free relocation in the bustling city of New York. Contact us today for expert moving companies in NYC and experience a seamless transition to your new home.",
// 		hero: newYorkHero,
// 		about: newYorkAbout,
// 		stats: newYorkStats,
// 		benefits: newYorkBenefits,
// 		cost: newYorkCost,
// 		whodBeSuited: newYorkWhodBeSuited,
// 		topCities: newYorkTopCities,
// 		schools: newYorkSchools,
// 		universities: newYorkUniversities,
// 		whereToWork: newYorkWhereToWork,
// 		vacation: newYorkVacation,
// 	},
// 	{
// 		slug: 'north-carolina',
// 		metaTitle: 'Trusted Greensboro Movers | Professional Moving Services',
// 		metaDescription:
// 			"Looking for reliable movers in Greensboro, NC? Look no further. Our professional moving services in Greensboro ensure a smooth and stress-free relocation. Whether you need local movers, assistance with moving services, or affordable options, we've got you covered. Contact us today for a seamless moving experience with our trusted Greensboro moving companies.",
// 		hero: northCarolinaHero,
// 		about: northCarolinaAbout,
// 		stats: northCarolinaStats,
// 		benefits: northCarolinaBenefits,
// 		cost: northCarolinaCost,
// 		whodBeSuited: northCarolinaWhodBeSuited,
// 		topCities: northCarolinaTopCities,
// 		schools: northCarolinaSchools,
// 		universities: northCarolinaUniversities,
// 		whereToWork: northCarolinaWhereToWork,
// 		vacation: northCarolinaVacation,
// 	},
// 	{
// 		slug: 'north-dakota',
// 		metaTitle: 'Trusted Movers from Los Angeles to North Dakota | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from Los Angeles to North Dakota? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in North Dakota.',
// 		hero: northDakotaHero,
// 		about: northDakotaAbout,
// 		stats: northDakotaStats,
// 		benefits: northDakotaBenefits,
// 		cost: northDakotaCost,
// 		whodBeSuited: northDakotaWhodBeSuited,
// 		topCities: northDakotaTopCities,
// 		schools: northDakotaSchools,
// 		universities: northDakotaUniversities,
// 		whereToWork: northDakotaWhereToWork,
// 		vacation: northDakotaVacation,
// 	},
// 	{
// 		slug: 'ohio',
// 		metaTitle: 'Trusted Movers from Los Angeles to Ohio | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from Los Angeles to Ohio? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in Ohio.',
// 		hero: ohioHero,
// 		about: ohioAbout,
// 		stats: ohioStats,
// 		benefits: ohioBenefits,
// 		cost: ohioCost,
// 		whodBeSuited: ohioWhodBeSuited,
// 		topCities: ohioTopCities,
// 		schools: ohioSchools,
// 		universities: ohioUniversities,
// 		whereToWork: ohioWhereToWork,
// 		vacation: ohioVacation,
// 	},
// 	{
// 		slug: 'oklahoma',
// 		metaTitle: 'Trusted Movers from Oklahoma City to Los Angeles | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from Oklahoma City to Los Angeles? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in Los Angeles.',
// 		hero: oklahomaHero,
// 		about: oklahomaAbout,
// 		stats: oklahomaStats,
// 		benefits: oklahomaBenefits,
// 		cost: oklahomaCost,
// 		whodBeSuited: oklahomaWhodBeSuited,
// 		topCities: oklahomaTopCities,
// 		schools: oklahomaSchools,
// 		universities: oklahomaUniversities,
// 		whereToWork: oklahomaWhereToWork,
// 		vacation: oklahomaVacation,
// 	},
// 	{
// 		slug: 'oregon',
// 		metaTitle: 'Reliable Moving Services in Portland, Oregon | Star Van Lines',
// 		metaDescription:
// 			'Planning a move in Portland, Oregon? Trust Star Van Lines for reliable and professional moving services. Our experienced team specializes in handling all aspects of your move, ensuring a seamless transition to your new home. Discover our trusted moving services in Portland, Oregon. Contact us today!',
// 		hero: oregonHero,
// 		about: oregonAbout,
// 		stats: oregonStats,
// 		benefits: oregonBenefits,
// 		cost: oregonCost,
// 		whodBeSuited: oregonWhodBeSuited,
// 		topCities: oregonTopCities,
// 		schools: oregonSchools,
// 		universities: oregonUniversities,
// 		whereToWork: oregonWhereToWork,
// 		vacation: oregonVacation,
// 	},
// 	{
// 		slug: 'pennsylvania',
// 		metaTitle: 'Smooth Moving to Pennsylvania from California | Star Van Lines Movers',
// 		metaDescription:
// 			'Planning a move to Pennsylvania from California? Trust Star Van Lines Movers for a smooth and hassle-free relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in Pennsylvania.',
// 		hero: pennsylvaniaHero,
// 		about: pennsylvaniaAbout,
// 		stats: pennsylvaniaStats,
// 		benefits: pennsylvaniaBenefits,
// 		cost: pennsylvaniaCost,
// 		whodBeSuited: pennsylvaniaWhodBeSuited,
// 		topCities: pennsylvaniaTopCities,
// 		schools: pennsylvaniaSchools,
// 		universities: pennsylvaniaUniversities,
// 		whereToWork: pennsylvaniaWhereToWork,
// 		vacation: pennsylvaniaVacation,
// 	},
// 	{
// 		slug: 'rhode-island',
// 		metaTitle: 'Smooth Moving to California from Rhode Island | Star Van Lines Movers',
// 		metaDescription:
// 			'Planning a move to California from Rhode Island? Trust Star Van Lines Movers for a smooth and stress-free relocation. Our experienced team of movers will handle every aspect of your move, ensuring a seamless transition to your new home.',
// 		hero: rhodeIslandHero,
// 		about: rhodeIslandAbout,
// 		stats: rhodeIslandStats,
// 		benefits: rhodeIslandBenefits,
// 		cost: rhodeIslandCost,
// 		whodBeSuited: rhodeIslandWhodBeSuited,
// 		topCities: rhodeIslandTopCities,
// 		schools: rhodeIslandSchools,
// 		universities: rhodeIslandUniversities,
// 		whereToWork: rhodeIslandWhereToWork,
// 		vacation: rhodeIslandVacation,
// 	},
// 	{
// 		slug: 'south-carolina',
// 		metaTitle: 'Trusted SC Movers | Reliable Moving Services in South Carolina',
// 		metaDescription:
// 			"Planning a move in South Carolina? Trust our SC movers for reliable and professional moving services. Whether you're looking for movers in Charleston, SC or the surrounding areas, our local movers provide efficient and hassle-free relocations. Contact us today for a seamless experience with trusted house movers in Charleston, SC and the wider region.",
// 		hero: southCarolinaHero,
// 		about: southCarolinaAbout,
// 		stats: southCarolinaStats,
// 		benefits: southCarolinaBenefits,
// 		cost: southCarolinaCost,
// 		whodBeSuited: southCarolinaWhodBeSuited,
// 		topCities: southCarolinaTopCities,
// 		schools: southCarolinaSchools,
// 		universities: southCarolinaUniversities,
// 		whereToWork: southCarolinaWhereToWork,
// 		vacation: southCarolinaVacation,
// 	},
// 	{
// 		slug: 'south-dakota',
// 		metaTitle: 'Trusted Movers from Los Angeles to South Dakota | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from Los Angeles to South Dakota? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in South Dakota.',
// 		hero: southDakotaHero,
// 		about: southDakotaAbout,
// 		stats: southDakotaStats,
// 		benefits: southDakotaBenefits,
// 		cost: southDakotaCost,
// 		whodBeSuited: southDakotaWhodBeSuited,
// 		topCities: southDakotaTopCities,
// 		schools: southDakotaSchools,
// 		universities: southDakotaUniversities,
// 		whereToWork: southDakotaWhereToWork,
// 		vacation: southDakotaVacation,
// 	},
// 	{
// 		slug: 'tennessee',
// 		metaTitle: 'Smooth Moving from Tennessee to California | Star Van Lines Movers',
// 		metaDescription:
// 			'Planning a move from Tennessee to California? Trust Star Van Lines Movers for a smooth and hassle-free relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in California.',
// 		hero: tennesseeHero,
// 		about: tennesseeAbout,
// 		stats: tennesseeStats,
// 		benefits: tennesseeBenefits,
// 		cost: tennesseeCost,
// 		whodBeSuited: tennesseeWhodBeSuited,
// 		topCities: tennesseeTopCities,
// 		schools: tennesseeSchools,
// 		universities: tennesseeUniversities,
// 		whereToWork: tennesseeWhereToWork,
// 		vacation: tennesseeVacation,
// 	},
// 	{
// 		slug: 'utah',
// 		metaTitle: 'Reliable Movers in Salt Lake City, Utah | Star Van Lines Movers',
// 		metaDescription:
// 			'When it comes to moving in Salt Lake City, Utah, trust Star Van Lines Movers for a seamless experience. Our dedicated team of movers in SLC provides exceptional service and handles your belongings with care. Contact us today for reliable and professional moving services in Salt Lake City.',
// 		hero: utahHero,
// 		about: utahAbout,
// 		stats: utahStats,
// 		benefits: utahBenefits,
// 		cost: utahCost,
// 		whodBeSuited: utahWhodBeSuited,
// 		topCities: utahTopCities,
// 		schools: utahSchools,
// 		universities: utahUniversities,
// 		whereToWork: utahWhereToWork,
// 		vacation: utahVacation,
// 	},
// 	{
// 		slug: 'vermont',
// 		metaTitle: 'Trusted Movers from Los Angeles to Vermont | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from Los Angeles to Vermont? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in Vermont.',
// 		hero: vermontHero,
// 		about: vermontAbout,
// 		stats: vermontStats,
// 		benefits: vermontBenefits,
// 		cost: vermontCost,
// 		whodBeSuited: vermontWhodBeSuited,
// 		topCities: vermontTopCities,
// 		schools: vermontSchools,
// 		universities: vermontUniversities,
// 		whereToWork: vermontWhereToWork,
// 		vacation: vermontVacation,
// 	},
// 	{
// 		slug: 'virginia',
// 		metaTitle: 'Efficient Moving to Virginia from California | Star Van Lines Movers',
// 		metaDescription:
// 			'Star Van Lines Movers is your trusted choice for efficient moving from California to Virginia. With our expertise and dedication to customer satisfaction, we ensure a seamless and stress-free relocation.',
// 		hero: virginiaHero,
// 		about: virginiaAbout,
// 		stats: virginiaStats,
// 		benefits: virginiaBenefits,
// 		cost: virginiaCost,
// 		whodBeSuited: virginiaWhodBeSuited,
// 		topCities: virginiaTopCities,
// 		schools: virginiaSchools,
// 		universities: virginiaUniversities,
// 		whereToWork: virginiaWhereToWork,
// 		vacation: virginiaVacation,
// 	},
// 	{
// 		slug: 'washington',
// 		metaTitle: 'Trusted Movers from Los Angeles to Washington | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from Los Angeles to Washington? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in Washington.',
// 		hero: washingtonHero,
// 		about: washingtonAbout,
// 		stats: washingtonStats,
// 		benefits: washingtonBenefits,
// 		cost: washingtonCost,
// 		whodBeSuited: washingtonWhodBeSuited,
// 		topCities: washingtonTopCities,
// 		schools: washingtonSchools,
// 		universities: washingtonUniversities,
// 		whereToWork: washingtonWhereToWork,
// 		vacation: washingtonVacation,
// 	},
// 	{
// 		slug: 'west-virginia',
// 		metaTitle: 'Smooth Moving from Virginia to Los Angeles | Star Van Lines Movers',
// 		metaDescription:
// 			' Planning a move from Virginia to Los Angeles? Trust Star Van Lines Movers for a smooth and hassle-free relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in Los Angeles.',
// 		hero: westVirginiaHero,
// 		about: westVirginiaAbout,
// 		stats: westVirginiaStats,
// 		benefits: westVirginiaBenefits,
// 		cost: westVirginiaCost,
// 		whodBeSuited: westVirginiaWhodBeSuited,
// 		topCities: westVirginiaTopCities,
// 		schools: westVirginiaSchools,
// 		universities: westVirginiaUniversities,
// 		whereToWork: westVirginiaWhereToWork,
// 		vacation: westVirginiaVacation,
// 	},
// 	{
// 		slug: 'wisconsin',
// 		metaTitle: 'Trusted Movers from Los Angeles to Wisconsin | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from Los Angeles to Wisconsin? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in Wisconsin.',
// 		hero: wisconsinHero,
// 		about: wisconsinAbout,
// 		stats: wisconsinStats,
// 		benefits: wisconsinBenefits,
// 		cost: wisconsinCost,
// 		whodBeSuited: wisconsinWhodBeSuited,
// 		topCities: wisconsinTopCities,
// 		schools: wisconsinSchools,
// 		universities: wisconsinUniversities,
// 		whereToWork: wisconsinWhereToWork,
// 		vacation: wisconsinVacation,
// 	},
// 	{
// 		slug: 'wyoming',
// 		metaTitle: 'Trusted Movers from Los Angeles to Wyoming | Star Van Lines Movers',
// 		metaDescription:
// 			'Moving from Los Angeles to Wyoming? Trust Star Van Lines Movers for a reliable and efficient relocation. Our experienced team specializes in long-distance moves, ensuring a seamless transition to your new home in Wyoming.',
// 		hero: wyomingHero,
// 		about: wyomingAbout,
// 		stats: wyomingStats,
// 		benefits: wyomingBenefits,
// 		cost: wyomingCost,
// 		whodBeSuited: wyomingWhodBeSuited,
// 		topCities: wyomingTopCities,
// 		schools: wyomingSchools,
// 		universities: wyomingUniversities,
// 		whereToWork: wyomingWhereToWork,
// 		vacation: wyomingVacation,
// 	},
// ];